# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more informatgion see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on : [push, pull_request]
permissions:
  contents: write
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps: 
  
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file devop_dataframe/pom.xml
    - name: step 4 show resultat
      run: ls -a
        
    - name: step 5 run test
      run: mvn -f devop_dataframe/pom.xml test
      
    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

    - name: Commit the badge (if it changed)
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'hacenesuper'
          git config --global user.email 'haceneamrane22@gmail.com'
          git add -A
          git commit -m "Autogenerated JaCoCo coverage badge"
          git push
          Username: 'hacenesuper'
          Password: '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'
        fi

    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/
    #connecting to docker hub  
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      #build docker image    
    - name: docker build image
      run: |
          docker build -t dataframe:latest .
    - name: docker push
      #push to docker hub
      run: |
          docker tag dataframe hacenesuper/dataframe:latest
          docker push hacenesuper/dataframe:latest          
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
